language: ruby
sudo: false
cache: bundler
rvm:
 - 2.3.1
 - 2.2.5
 - 2.1.9
addons:
  apt:
    packages:
    - libicu-dev
before_script:
- git config --global user.email "test@example.com"
- git config --global user.name "Test"
