language: ruby
cache: bundler
sudo: false
rvm:
  - 2.6.0
  - 2.5.3
  - 2.4.5
  - 2.3.8
before_install:
  - gem update --system
  - gem install bundler --no-document
addons:
  apt:
    packages:
    - libicu-dev
before_script:
- git config --global user.email "test@example.com"
- git config --global user.name "Test"
after_success:
  - bundle exec codeclimate-test-reporter
