language: ruby
sudo: false
cache: bundler
rvm:
 - 2.4.1
 - 2.3.3
 - 2.2.6
 - 2.1.9
addons:
  apt:
    packages:
    - libicu-dev
before_script:
- git config --global user.email "test@example.com"
- git config --global user.name "Test"
after_success:
  - bundle exec codeclimate-test-reporter
