language: ruby
sudo: false
cache: bundler
rvm:
  - 2.5.3
  - 2.4.5
  - 2.3.8
  - 2.2.10
addons:
  apt:
    packages:
    - libicu-dev
before_script:
- git config --global user.email "test@example.com"
- git config --global user.name "Test"
after_success:
  - bundle exec codeclimate-test-reporter
