language: ruby
cache: bundler
sudo: false
rvm:
  - 2.7.0
  - 2.6.5
  - 2.5.7
  - 2.4.9
  - ruby-head
addons:
  apt:
    packages:
    - libicu-dev
before_script:
- git config --global user.email "test@example.com"
- git config --global user.name "Test"
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
